# Numpy


In [1]:
# create array : 1d
import numpy as np
array_1d = np.array([2,3,4,5,7])
type(array_1d)

numpy.ndarray

In [5]:
# create array : 2d
array_2d = np.array([[1, 2, 3],
              [4, 5, 6]])
print(array_2d)



[[1 2 3]
 [4 5 6]]


In [4]:
# create array : 3d
array_3d = np.array([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]]
])

print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# create Special NumPy Arrays, 1. Zeros Array
import numpy as np

a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# create Special NumPy Arrays, 1. ones Array
a = np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
#📌 3. Eye (Identity Matrix)
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#📌 4. Arange (Range numbers)
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [14]:
a = np.array([[1,2,4],[2,3,5]])
print(a.shape)

(2, 3)


# array slicing

In [1]:
import numpy as np
a = np.array([10,20,30,40,50,60,70,80])
print(a[2:6])

[30 40 50 60]


In [16]:
import numpy as np

a = np.array([
    [100, 101, 102, 103],
    [200, 201, 202, 203]
])
print(a[1])
print(a[1, 1:3])

[200 201 202 203]
[201 202]


In [17]:
import numpy as np

a = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])
print(a.shape)

(2, 2, 3)


In [18]:
print(a[0])

[[1 2 3]
 [4 5 6]]


In [19]:
print(a[1])

[[ 7  8  9]
 [10 11 12]]


In [20]:
print(a[1, 0, 2])

9


# 🧠 NumPy linspace()

In [25]:
#📌 Example calculation
#start = 1
#stop = 10
#num = 5

#step = (10 - 1) / 4 = 2.25
#___________________________
a = np.linspace(1, 5, 10)
print(a)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [21]:
import numpy as np

a = np.linspace(1, 10, 5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [22]:
a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


# 🧠 NumPy Random Array 

In [26]:
import numpy as np

a = np.random.rand(3, 3)
print(a)

[[0.94996223 0.62557371 0.83132902]
 [0.74729205 0.82152523 0.01164212]
 [0.14504698 0.19530613 0.36714819]]


In [27]:
a = np.random.randint(1, 100, (3, 3))
print(a)

[[48 72 91]
 [94 62  7]
 [65 66 45]]


# arange()

In [2]:
import numpy as np
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


# Random Array (rand):

In [3]:
import numpy as np
a = np.random.rand(2,4)
print(a)

[[0.63253713 0.59489981 0.79162104 0.09567407]
 [0.79136701 0.83271179 0.5333268  0.89378205]]


# Random Integer (randint)

In [5]:
import numpy as np
a = np.random.randint(10,50,(3,4))
print(a)

[[24 20 47 22]
 [15 13 42 22]
 [40 31 22 43]]


In [6]:
import numpy as np
a = np.random.randint(10,100,(6,7))
print(a)

[[90 33 12 82 34 55 13]
 [27 71 33 81 82 52 33]
 [32 16 73 68 66 59 99]
 [16 81 73 25 79 54 45]
 [55 68 77 48 13 94 39]
 [47 29 57 40 70 56 83]]


# 1.sum()

In [7]:
import numpy as np
a =np.array([10,20,30,40,50,60]) # addition method
print(np.sum(a))

210


# 2. mean() → Average

In [8]:
import numpy as np
a =np.array([10,20,30,40,50,60]) # addition method or % 5
print(np.mean(a))

35.0


# 3. max() → Largest Value

In [9]:
import numpy as np
a =np.array([10,20,30,40,50,60]) # max value
print(np.max(a))

60


# 4. min() → Smallest Value

In [10]:
import numpy as np
a =np.array([10,20,30,40,50,60]) # smallest value
print(np.min(a))

10


# 5. std() → Standard Deviation

In [11]:
import numpy as np
a =np.array([10,20,30,40,50,60]) 
print(np.std(a))

17.07825127659933


# 6. var() → Variance

In [12]:
import numpy as np
a =np.array([10,20,30,40,50,60]) 
print(np.var(a))

291.6666666666667


# 7. sqrt() → Square Root

In [13]:
import numpy as np
a =np.array([10,20,30,40,50,60]) 
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]


# 8. square() → Square

In [14]:
import numpy as np
a =np.array([10,20,30,40,50,60]) 
print(np.square(a))

[ 100  400  900 1600 2500 3600]


In [ ]:
# 9. sort() → Ascending Order